stages:
  - sast-scan
  - sast-upload
  - docker_start
  - dast-scan
  - docker_stop

variables:
  DOCKER_REGISTRY: docker.ekseed.org
  IMAGE_NAME: ${CI_PROJECT_NAME}
  FTFY_APPLICATION: "petclinic"
  FTFY_SSC_URL: "https://ssc.ekseed.org/ssc"
  SCDAST_SETTINGS: "1b17660a-f565-4913-9b76-7e42d94e918c"


sast-scan:
  stage: sast-scan
  script:
    - /fortify/SCA_21.2.1/bin/sourceanalyzer -verbose -debug -b "petclinic-${CI_COMMIT_BRANCH}" -clean
    - ./mvnw dependency:copy-dependencies
    - ls -al target/dependency
    - /fortify/SCA_21.2.1/bin/sourceanalyzer -verbose -debug -b "petclinic-${CI_COMMIT_BRANCH}" -cp target/dependency/*.jar src/main/**/*.java
    - /fortify/SCA_21.2.1/bin/sourceanalyzer -verbose -debug -b "petclinic-${CI_COMMIT_BRANCH}" -cp target/dependency/*.jar src/main/**/*.jsp
    - /fortify/SCA_21.2.1/bin/sourceanalyzer -verbose -debug -b "petclinic-${CI_COMMIT_BRANCH}" -show-files
    - /fortify/SCA_21.2.1/bin/sourceanalyzer -verbose -debug -b "petclinic-${CI_COMMIT_BRANCH}" -scan -f "petclinic-${CI_COMMIT_BRANCH}.fpr"
  artifacts:
    name: FPR_FILE
    paths:
      - "petclinic-${CI_COMMIT_BRANCH}.fpr"
  tags:
    - fortify-ubuntu
    - shell


sast-upload:
  stage: sast-upload
  dependencies:
    - sast-scan
  script:
    - /fortify/SCA_21.2.1/bin/fortifyclient -debug -url $FTFY_SSC_URL -authtoken $FTFY_CI_TOKEN uploadFPR -application petclinic -applicationVersion $CI_COMMIT_BRANCH -file "petclinic-${CI_COMMIT_BRANCH}.fpr"
  tags:
    - fortify-ubuntu
    - shell

package_n_start:
  stage: docker_start
  dependencies:
    - sast-scan
  script:
    - ./mvnw package
    ## Login to docker registry
    - sudo docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${DOCKER_REGISTRY}
    - sudo docker build . -t docker.ekseed.org/petclinic:$CI_COMMIT_SHORT_SHA
    - sudo docker run -d --name petclinic-$CI_COMMIT_SHORT_SHA --rm -p 8880:8080 docker.ekseed.org/petclinic:$CI_COMMIT_SHORT_SHA
  tags:
    - fortify-ubuntu
    - shell
      
dast-scan:
  stage: dast-scan
  image: docker.ekseed.org/fcli:ubuntu

  script:
    - fcli auth login ssc --url ${FTFY_SSC_URL} --token "${FTFY_ENC_TOKEN}"
    - fcli dast sc-dast start -s  ${SCDAST_SETTINGS} --url http://fortify-ubuntu.ekseed.org:8880/ -n "petclinic-${CI_COMMIT_BRANCH}" --format json > start-output.txt
    - 'scanid=$(cat start-output.txt | grep -oP "(?<=\"id\" : )\d*")'
    - echo "scan $scanid started"
    - fcli get sc-dast scan results -i $scanid -w
  tags :
    - docker-exec

stop_app:
  stage: docker_stop
  script:
    ## Login to docker registry
    - sudo docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${DOCKER_REGISTRY}
    - sudo docker stop petclinic-$CI_COMMIT_SHORT_SHA
  tags:
    - fortify-ubuntu
    - shell


